#!/usr/bin/env bash

# Script that verifies core dependencies can be imported.

action() {
    local shell_is_zsh="$( [ -z "${ZSH_VERSION}" ] && echo "false" || echo "true" )"
    local this_file="$( ${shell_is_zsh} && echo "${(%):-%x}" || echo "${BASH_SOURCE[0]}" )"
    local this_dir="$( cd "$( dirname "${this_file}" )" && pwd )"
    local st_entanglement_dir="$( dirname "${this_dir}" )"

    (
        cd "${st_entanglement_dir}" && \
        python -m unittest tests.test_imports
    )
}
action "$@"
